name: thelastlife
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  go_router: ^7.1.1
  slang: ^3.18.1
  slang_flutter: ^3.18.0
  cupertino_icons: ^1.0.2
  audioplayers: ^4.0.0
  get_storage: ^2.1.1
  dynamic_color: ^1.6.3
  flutter_svg: ^2.0.6
  carousel_slider: ^4.2.1

  restart_app: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/icons/flags/svg/
    - assets/sfx/
    - assets/music/
    - assets/icons/logo.svg